- name: crictl
  ansible.builtin.unarchive:
    src: https://github.com/kubernetes-sigs/cri-tools/releases/download/{{ CRICTL_VERSION }}/crictl-{{ CRICTL_VERSION }}-{{ BIN_ARCH }}.tar.gz
    dest: /usr/local/bin/
    remote_src: yes

- name: runc
  get_url:
    url: https://github.com/opencontainers/runc/releases/download/{{ RUNC_VERSION }}/runc.{{ RUNC_ARCH }}
    dest: /usr/local/bin/

- name: cni-plugins
  ansible.builtin.unarchive:
    src: https://github.com/containernetworking/plugins/releases/download/{{ CNI_PLUGINS_VERSION }}/cni-plugins-{{ BIN_ARCH }}-{{ CNI_PLUGINS_VERSION }}.tgz
    dest: /usr/local/bin/
    remote_src: yes

- name: containerd
  ansible.builtin.unarchive:
    src: https://github.com/containerd/containerd/releases/download/v{{ CONTAINERD_VERSION }}/containerd-{{ CONTAINERD_VERSION }}-{{ BIN_ARCH }}.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
